from pathlib import Path
import csv
import cv2

from ultralytics import YOLO
from ocr import baseline_ocr, improved_ocr


# =========================
# Paths
# =========================

BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_PATH = (
    BASE_DIR
    / "runs"
    / "license_plate_detection"
    / "weights"
    / "best.pt"
)

TEST_IMAGES_DIR = (
    BASE_DIR
    / "dataset"
    / "yolo"
    / "images"
    / "test"
)

EVALUATION_DIR = (
    BASE_DIR
    / "runs"
    / "ocr_evaluation"
)

csv_files = sorted(
    EVALUATION_DIR.glob("*.csv")
)

# Exclude files generated by analysis/re-evaluation
csv_files = [
    f for f in csv_files
    if f.name not in {
        "ocr_summary.csv",
        "ocr_summary_v2.csv",
        "ocr_summary_v3.csv",
        "ocr_results_v3.csv",
    }
]

if not csv_files:
    print("ERROR: No previous OCR results CSV found.")
    print(f"Checked folder: {EVALUATION_DIR}")
    raise SystemExit(1)

# Use the most recently modified OCR results file
OLD_CSV = max(
    csv_files,
    key=lambda f: f.stat().st_mtime
)

print("Using previous OCR results:")
print(OLD_CSV)

NEW_CSV = (
    BASE_DIR
    / "runs"
    / "ocr_evaluation"
    / "ocr_results_v3.csv"
)

CROPS_DIR = (
    BASE_DIR
    / "runs"
    / "ocr_evaluation"
    / "plate_crops_v3"
)

CROPS_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# =========================
# Check Files
# =========================

if not OLD_CSV.exists():
    print("ERROR: Old OCR results file not found:")
    print(OLD_CSV)
    raise SystemExit(1)

if not MODEL_PATH.exists():
    print("ERROR: YOLO model not found:")
    print(MODEL_PATH)
    raise SystemExit(1)


# =========================
# Character Accuracy
# =========================

def character_accuracy(predicted, ground_truth):

    predicted = predicted.upper()
    ground_truth = ground_truth.upper()

    if not ground_truth:
        return 0.0

    correct = 0

    for i in range(
        min(
            len(predicted),
            len(ground_truth)
        )
    ):

        if predicted[i] == ground_truth[i]:
            correct += 1

    return correct / len(ground_truth)


# =========================
# Exact Match
# =========================

def exact_match(
    predicted,
    ground_truth
):

    return (
        predicted.upper()
        == ground_truth.upper()
    )


# =========================
# Load Old Results
# =========================

old_results = []

with open(
    OLD_CSV,
    "r",
    encoding="utf-8"
) as file:

    reader = csv.DictReader(file)

    for row in reader:
        old_results.append(row)


print("=" * 70)
print("AUTOMATIC OCR RE-EVALUATION")
print("=" * 70)

print(
    f"Images to evaluate: "
    f"{len(old_results)}"
)


# =========================
# Load YOLO
# =========================

print("\nLoading YOLO model...")

model = YOLO(
    str(MODEL_PATH)
)

print("Model loaded successfully.")


# =========================
# Results
# =========================

results = []


# =========================
# Process Images
# =========================

for index, row in enumerate(
    old_results,
    start=1
):

    image_name = row["image"]

    ground_truth = (
        row["ground_truth"]
        .strip()
        .upper()
    )

    image_path = (
        TEST_IMAGES_DIR
        / image_name
    )

    print(
        f"\n[{index}/{len(old_results)}] "
        f"{image_name}"
    )

    # -------------------------
    # Read image
    # -------------------------

    image = cv2.imread(
        str(image_path)
    )

    if image is None:

        print(
            "Could not read image."
        )

        continue

    # -------------------------
    # YOLO Detection
    # -------------------------

    detections = model(
        image,
        conf=0.40,
        verbose=False
    )

    best_box = None
    best_conf = 0.0

    for result in detections:

        if result.boxes is None:
            continue

        for box in result.boxes:

            confidence = float(
                box.conf[0]
                .cpu()
                .numpy()
            )

            if confidence > best_conf:

                best_conf = confidence

                best_box = (
                    box.xyxy[0]
                    .cpu()
                    .numpy()
                    .astype(int)
                )

    # -------------------------
    # No Detection
    # -------------------------

    if best_box is None:

        print(
            "No license plate detected."
        )

        baseline = ""
        improved = ""

    else:

        x1, y1, x2, y2 = best_box

        h, w = image.shape[:2]

        x1 = max(
            0,
            min(x1, w - 1)
        )

        x2 = max(
            0,
            min(x2, w - 1)
        )

        y1 = max(
            0,
            min(y1, h - 1)
        )

        y2 = max(
            0,
            min(y2, h - 1)
        )

        plate_crop = image[
            y1:y2,
            x1:x2
        ]

        if plate_crop.size == 0:

            print(
                "Invalid crop."
            )

            baseline = ""
            improved = ""

        else:

            # -------------------------
            # Save Crop
            # -------------------------

            crop_path = (
                CROPS_DIR
                / image_name
            )

            cv2.imwrite(
                str(crop_path),
                plate_crop
            )

            # -------------------------
            # OCR
            # -------------------------

            baseline = baseline_ocr(
                plate_crop
            )

            improved = improved_ocr(
                plate_crop
            )

    # -------------------------
    # Accuracy
    # -------------------------

    baseline_acc = character_accuracy(
        baseline,
        ground_truth
    )

    improved_acc = character_accuracy(
        improved,
        ground_truth
    )

    baseline_exact = exact_match(
        baseline,
        ground_truth
    )

    improved_exact = exact_match(
        improved,
        ground_truth
    )

    # -------------------------
    # Print
    # -------------------------

    print(
        f"Ground Truth : {ground_truth}"
    )

    print(
        f"Baseline     : "
        f"{baseline or 'N/A'}"
    )

    print(
        f"Improved     : "
        f"{improved or 'N/A'}"
    )

    print(
        f"Baseline Acc : "
        f"{baseline_acc * 100:.2f}%"
    )

    print(
        f"Improved Acc : "
        f"{improved_acc * 100:.2f}%"
    )

    # -------------------------
    # Store
    # -------------------------

    results.append({
        "image": image_name,
        "ground_truth": ground_truth,
        "baseline": baseline,
        "improved": improved,
        "baseline_char_accuracy": baseline_acc,
        "improved_char_accuracy": improved_acc,
        "baseline_exact": int(
            baseline_exact
        ),
        "improved_exact": int(
            improved_exact
        ),
    })


# =========================
# Save Results
# =========================

fieldnames = [
    "image",
    "ground_truth",
    "baseline",
    "improved",
    "baseline_char_accuracy",
    "improved_char_accuracy",
    "baseline_exact",
    "improved_exact",
]


with open(
    NEW_CSV,
    "w",
    newline="",
    encoding="utf-8"
) as file:

    writer = csv.DictWriter(
        file,
        fieldnames=fieldnames
    )

    writer.writeheader()

    writer.writerows(
        results
    )


# =========================
# Final Statistics
# =========================

if results:

    baseline_accuracy = sum(
        r["baseline_char_accuracy"]
        for r in results
    ) / len(results)

    improved_accuracy = sum(
        r["improved_char_accuracy"]
        for r in results
    ) / len(results)

    baseline_exact_accuracy = sum(
        r["baseline_exact"]
        for r in results
    ) / len(results)

    improved_exact_accuracy = sum(
        r["improved_exact"]
        for r in results
    ) / len(results)

    improved_better = sum(
        r["improved_char_accuracy"]
        > r["baseline_char_accuracy"]
        for r in results
    )

    baseline_better = sum(
        r["baseline_char_accuracy"]
        > r["improved_char_accuracy"]
        for r in results
    )

    same_result = sum(
        r["baseline_char_accuracy"]
        == r["improved_char_accuracy"]
        for r in results
    )

    baseline_failures = sum(
        not r["baseline"]
        for r in results
    )

    improved_failures = sum(
        not r["improved"]
        for r in results
    )

    print("\n")
    print("=" * 70)
    print("FINAL V3 OCR RESULTS")
    print("=" * 70)

    print(
        f"Total images: "
        f"{len(results)}"
    )

    print("\nCHARACTER ACCURACY")

    print(
        f"Baseline : "
        f"{baseline_accuracy * 100:.2f}%"
    )

    print(
        f"Improved : "
        f"{improved_accuracy * 100:.2f}%"
    )

    print("\nEXACT MATCH")

    print(
        f"Baseline : "
        f"{baseline_exact_accuracy * 100:.2f}%"
    )

    print(
        f"Improved : "
        f"{improved_exact_accuracy * 100:.2f}%"
    )

    print("\nCOMPARISON")

    print(
        f"Improved better : "
        f"{improved_better}"
    )

    print(
        f"Baseline better : "
        f"{baseline_better}"
    )

    print(
        f"Same result     : "
        f"{same_result}"
    )

    print("\nOCR FAILURES")

    print(
        f"Baseline failures : "
        f"{baseline_failures}"
    )

    print(
        f"Improved failures : "
        f"{improved_failures}"
    )

    difference = (
        improved_accuracy
        - baseline_accuracy
    )

    print("\nOVERALL DIFFERENCE")

    if difference > 0:

        print(
            f"Improved OCR increased "
            f"accuracy by "
            f"{difference * 100:.2f} "
            f"percentage points."
        )

    elif difference < 0:

        print(
            f"Improved OCR decreased "
            f"accuracy by "
            f"{abs(difference) * 100:.2f} "
            f"percentage points."
        )

    else:

        print(
            "No difference."
        )


print("\n")
print("=" * 70)

print("New results saved to:")

print(NEW_CSV)

print("=" * 70)
